# Generated by Django 5.1.5 on 2025-01-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_game_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="categories",
            field=models.ManyToManyField(null=True, to="api.category"),
        ),
    ]
