# Generated by Django 5.1.5 on 2025-03-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_game_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="categories",
            field=models.ManyToManyField(blank=True, to="api.category"),
        ),
    ]
