# Generated by Django 5.1.5 on 2025-03-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_profile_public_alter_game_categories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="creation_date",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="modification_date",
            new_name="modified",
        ),
        migrations.AlterField(
            model_name="game",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="games_in_category", to="api.category"
            ),
        ),
    ]
