# Generated by Django 5.1.5 on 2025-04-10 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_creation_date_game_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='created',
        ),
        migrations.RemoveField(
            model_name='game',
            name='modified',
        ),
        migrations.AddField(
            model_name='game',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='format_version',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='game',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
