# Generated by Django 5.1.5 on 2025-04-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_game_created_remove_game_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rules',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
