# Generated by Django 5.1.5 on 2025-04-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_game_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
